### ISSUE TITLE
Bug in F1 score computation

### ISSUE THREAD

**Issue by trangham283** [martinmamql/Interpretable-Multimodal-Routing-for-Human-Multimodal-Language#3]
Hello, thank you for releasing the code! 

I'm wondering if [this line](https://github.com/martinmamql/multimodal_routing/blob/ba71b1d2549907e8bcc5d8ec634c6f5d86bbe824/src/eval_metrics.py#L50) for computing the F1 score is a bug (flipped order of truth and pred), or it's because of how your data is set up. If so, could you elaborate? 

A similar issue is raised [here](https://github.com/yaohungt/Multimodal-Transformer/issues/33).

**Comment by martinmamql** [comment]
Hi Trang,

Greetings! Thank you very much for pointing it out -- it is indeed a bug of evaluating the F1 score in MOSEI sentiment and I have corrected the code. Using the correct version, I can obtain an F1 score of over 82% within 20 epochs on MOSEI sentiment, using the default `run.sh` in the Github page, which is even better than the reported number in the paper (81.8%). More hyper-parameter tuning might help the performance.

Thank you very much for your post!

Sincerely,
Martin
