### ISSUE TITLE
About the dataset ‘mosei_emo’

### ISSUE THREAD

**Issue by Lilianzjl** [martinmamql/Interpretable-Multimodal-Routing-for-Human-Multimodal-Language#4]
Hello,

(Edited)

Thank you for releasing the code. It's massively helpful. 

I downloaded the data set according to the website you provided, but I had a problem loading the data:

`FileNotFoundError: [Errno 2] No such file or directory: '/XX/mosei_emo_data.pkl'`

I just changed the “DATASET” field of “run.sh” to "mosei_emo". There is no file "mosei_emo_data.pkl" in the dataset you provided. How can I solve this problem?

Thanks in advance.

**Comment by martinmamql** [comment]
Greetings! Sorry for the delay -- I will try to get back as soon as possible. Thank you for your understanding!

**Comment by martinmamql** [comment]
Hello Lilianzjl,

Greetings! I sincerely apologize for the delay. The new .zip link with the mosei_emo_data.pkl file is ready below:

https://www.dropbox.com/s/jf216k3jpwwum46/Archive.zip?dl=0

Please let me know if you have any questions.

Thank you very much!

**Comment by martinmamql** [comment]
Dataset link updated

**Comment by martinmamql** [comment]
https://www.dropbox.com/s/jf216k3jpwwum46/Archive.zip?dl=0
