### ISSUE TITLE
link to download the dataset in broken

### ISSUE THREAD

**Issue by srb-cv** [martinmamql/Interpretable-Multimodal-Routing-for-Human-Multimodal-Language#5]
Hi, I am trying to run some experiments with your method but I found that the link to the data is broken. Could you please fix it or point me to the correct link to the data?

**Comment by martinmamql** [comment]
Sorry for the problem, here is the dataset link:
[Data](https://www.dropbox.com/sh/hyzpgx1hp9nj37s/AAB7FhBqJOFDw2hEyvv2ZXHxa?dl=0)
Thanks for pointing this out!
